services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: trading-bot-postgres
    environment:
      - POSTGRES_DB=trading_bot
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=trading_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_user -d trading_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Server (Backend)
  api:
    build:
      context: .
      dockerfile: web-dashboard/Dockerfile.api
    container_name: trading-bot-api
    ports:
      - "8001:8001"
    environment:
      - TRADING_MODE=${TRADING_MODE:-paper}
      - USE_TESTNET=${USE_TESTNET:-true}
      - LLM_PROVIDER=${LLM_PROVIDER:-mock}
      - LLM_API_KEY=${LLM_API_KEY:-}
      - LLM_MODEL=${LLM_MODEL:-}
      - EXCHANGE=${EXCHANGE:-bybit}
      - SYMBOL=${SYMBOL:-BTC/USDT}
      - INITIAL_BALANCE=${INITIAL_BALANCE:-10000.0}
      - MAX_POSITION_SIZE=${MAX_POSITION_SIZE:-0.1}
      - STOP_LOSS_PERCENT=${STOP_LOSS_PERCENT:-2.0}
      - TAKE_PROFIT_PERCENT=${TAKE_PROFIT_PERCENT:-3.0}
      - RUN_INTERVAL_SECONDS=${RUN_INTERVAL_SECONDS:-300}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DATABASE_URL=postgresql://trading_user:trading_password@postgres:5432/trading_bot
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - trading-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend
  frontend:
    build:
      context: ./web-dashboard
      dockerfile: Dockerfile.frontend
    container_name: trading-bot-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Trading Bot (Optional - for running the actual bot)
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: trading-bot-main
    environment:
      - TRADING_MODE=${TRADING_MODE:-paper}
      - USE_TESTNET=${USE_TESTNET:-true}
      - LLM_PROVIDER=${LLM_PROVIDER:-mock}
      - LLM_API_KEY=${LLM_API_KEY:-}
      - LLM_MODEL=${LLM_MODEL:-}
      - EXCHANGE=${EXCHANGE:-bybit}
      - SYMBOL=${SYMBOL:-BTC/USDT}
      - INITIAL_BALANCE=${INITIAL_BALANCE:-10000.0}
      - MAX_POSITION_SIZE=${MAX_POSITION_SIZE:-0.1}
      - STOP_LOSS_PERCENT=${STOP_LOSS_PERCENT:-2.0}
      - TAKE_PROFIT_PERCENT=${TAKE_PROFIT_PERCENT:-3.0}
      - RUN_INTERVAL_SECONDS=${RUN_INTERVAL_SECONDS:-300}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - trading-network
    restart: unless-stopped
    profiles:
      - bot  # Only start when explicitly requested
    depends_on:
      - api

networks:
  trading-network:
    driver: bridge

volumes:
  data:
  logs:
  postgres_data:
